import Ignite

struct InlineSubtopicNavigation: HTML {
    let subTopics: [SubTopic]

    var body: some HTML {
        List(subTopics) { subTopic in
            Link(subTopic.name, target: "#\(subTopic.id)")
        }
        .class("subtopics-nav")
    }

    // Unfortunately Ignite doesn't expose conversion of Markup to raw HTML string, so this is generated by hand, because it needs to be injected in the article HTML in the post-processing step.
    var htmlString: String {
        let items = subTopics.map {
            ##"<li><a class="m-0" href="#\##($0.id)">\##($0.name)</a></li>"##
        }
        return """
            <ul class="subtopics-nav">
                \(items.joined(separator: "\n"))
            </ul>
            """
    }
}
